### ISSUE TITLE
(#22413) ValueError when a key present in `class_weight` is not found in labels

### ISSUE THREAD

**Issue by navn-r** [navn-r/scikit-learn#1]
Document your bug fixes and write test cases to demonstrate that the changes have been implemented correctly. Design these as ”customer acceptance” tests: i.e. a description of the steps a user needs to carry out to check that the items requested. Submit a set of tests, described in a form that would allow any user to download your new version of a scikit-learn component, run it, execute the tests, and determine that the software works correctly. 

You can assume that the user has a basic working knowledge of Python and scikit-learn. Write a brief technical commentary on how your changes affect the design and/or the code of scikit-learn. List all relevant scikit-learn source code files that were added, modified or removed as part of your implementation work.

**Task List**:

- [x] Submit PR to [scikit-learn/scikit-learn](https://github.com/scikit-learn/scikit-learn)
- [x] Document code changes, including description and implementation in [UTSCCSCD01/course-project-unbounded](https://github.com/UTSCCSCD01/course-project-unbounded)
- [x] Include UAT tests in the documentation, *if it can be coded, then submit code*, else images or detailed steps
